// front-react/src/components/navbar/Navbar.tsx
import { useStoreUser } from "../../store/useStoreUser";

export const Navbar = () => {
  const token = useStoreUser((state) => state.token);
  const setToken = useStoreUser((state) => state.setToken);
  const user = useStoreUser((state) => state.user);
  const haveToken = token !== "";

  const handleCerrarSesion = () => {
    localStorage.removeItem("token");
    setToken("");
  };

  return (
    <nav className="bg-gray-800 p-4 fixed top-0 w-full z-10">
      <div className="container mx-auto flex items-center justify-between">
        <span className="text-white text-lg font-semibold hover:cursor-pointer">
          TO-DO APP
        </span>

        <div className="flex items-center space-x-4">
          {haveToken ? (
            <>
              <a
                href="#"
                className="text-gray-300 hover:text-white hover:underline"
              >
                Inicio
              </a>

              <span className="text-gray-300">Bienvenido, {user.Username}</span>

              <button
                className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded"
                onClick={handleCerrarSesion}
              >
                Cerrar Sesión
              </button>
            </>
          ) : (
            <>
              <div className="text-white uppercase font-bold text-2xl">
                LOGIN
              </div>
            </>
          )}
        </div>
      </div>
    </nav>
  );
};

// front-angular/src/app/components/navbar/navbar.component.ts
import { Component, Input } from '@angular/core';
import { UserAuth, UserDTO } from '../../../types/types';
import { UserStateService } from '../../stores/user/user-state.service';
import { LocalStorageService } from '../../services/local-storage-service.service';
import { decodeToken } from '../../utils/decodeToken';
import { AuthService } from '../../services/auth-service.service';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [],
  templateUrl: './navbar.component.html',
  styles: ``,
})
export class NavbarComponent {
  user$: UserDTO = {
    UserID: 0,
    Username: '',
    Email: '',
    ToDoDTO: [],
  };

  haveToken: String = 'sdfas';

  constructor(
    private userState: UserStateService,
    private localStorage: LocalStorageService,
    private authService: AuthService
  ) {
    this.userState.token$.subscribe((token) => {
      this.haveToken = token;
    });

    this.haveToken = this.userState.token();
  }
  ngOnInit() {
    const token = this.localStorage.getItem('token');
    if (token) {
      const tokenDecoded = decodeToken(token);

      //aca hacer la consulta al backend para obtener el usuario
    }
    this.authService.getUser(1).subscribe((user) => {
      this.user$ = user;
    });
  }

  logout() {
    this.userState.setToken('');
    this.localStorage.removeItem('token');
    this.userState.setUser({
      UserID: 0,
      Username: '',
      Email: '',
      ToDoDTO: [],
    });
  }
}

<nav class="bg-gray-800 p-4 fixed top-0 w-full z-10">
  <div class="container mx-auto flex items-center justify-between">
    <span class="text-white text-lg font-semibold hover:cursor-pointer">
      TO-DO APP
    </span>

    <div class="flex items-center space-x-4">
      @if( haveToken ) {
      <div>
        <a href="#" class="text-gray-300 hover:text-white hover:underline">
          Inicio
        </a>

        <span class="text-gray-300">Bienvenido, {{ user$.Username }}</span>

        <button
          class="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded"
          (click)="logout()"
        >
          Cerrar Sesión
        </button>
      </div>

      } @else {

      <div>
        <div class="text-white uppercase font-bold text-2xl">LOGIN</div>
      </div>
      }
    </div>
  </div>
</nav>
